// Shared by the job entries and their corresponding project case studies.
export const experienceTechnologies = {
  generalDynamics: [
    'Java',
    'J2EE',
    'JPA',
    'Jenkins',
    'Python',
    'NumPy',
    'openpyxl',
    'SQL',
    'PL/SQL',
    'Bash',
    'Embedded Systems',
    'Linux',
    'RedHat Linux',
    'VMware vSphere',
    'Oracle Database',
    'Oracle WebLogic',
    'Oracle Exadata',
    'Oracle Business Intelligence (OBIEE)',
    'Oracle Data Integrator (ODI)',
    'Oracle GoldenGate',
    'MS SQL',
    'MySQL',
    'Eclipse',
    'Star Schema',
    '3NF',
    'Git',
    'Data integration',
  ],
  angelStudios: [
    'React',
    'Next.js',
    'Tailwind CSS',
    'i18n',
    'Vercel',
    'Braze',
    'Optimizely',
    'Segment',
    'Snowflake',
    'Bitmovin',
    'Cloudinary',
    'Contentful',
    'Crowdin',
    'GraphQL',
  ],
  oneOrigin: [
    'Python',
    'Flask',
    'AWS Neptune',
    'openCypher',
    'AWS',
    'Vue.js',
    'JavaScript',
    'PostgreSQL',
    'Tailwind CSS',
    'Jenkins',
    'Jira',
  ],
} as const;
