export function ShortcutIcon() {
  const cloudinaryCloudName = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;
  return (
    <>
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href={`https://res.cloudinary.com/${cloudinaryCloudName}/image/upload/ar_1.0,w_180,h_180/cory-siebler/favicon.png`}
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        sizes="152x152"
        href={`https://res.cloudinary.com/${cloudinaryCloudName}/image/upload/ar_1.0,w_152,h_152/cory-siebler/favicon.png`}
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        sizes="120x120"
        href={`https://res.cloudinary.com/${cloudinaryCloudName}/image/upload/ar_1.0,w_120,h_120/cory-siebler/favicon.png`}
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        sizes="76x76"
        href={`https://res.cloudinary.com/${cloudinaryCloudName}/image/upload/ar_1.0,w_76,h_76/cory-siebler/favicon.png`}
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        sizes="57x57"
        href={`https://res.cloudinary.com/${cloudinaryCloudName}/image/upload/ar_1.0,w_57,h_57/cory-siebler/favicon.png`}
        type="image/png"
      />
      <link
        rel="icon"
        href={`https://res.cloudinary.com/${cloudinaryCloudName}/image/upload/ar_1.0,w_57,h_57/cory-siebler/favicon.png`}
        type="image/png"
      />
    </>
  );
}
