name: Run TypeScript Checks

on:
  pull_request:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run TypeScript type checking
      - name: Run TypeScript type checking
        run: bun tsc --noEmit
